@ECHO OFF
REM ### CONFIGURE YOUR COM PORT HERE
set COMPORT=COM7

REM ### THE BELOW BAUD RATE MUST MATCH
REM ### YOUR TRANSCEIVER BAUD RATE!
mode %COMPORT% BAUD=9600 PARITY=n DATA=8 > NUL

REM TX Power 50W ; Memory-Channel 003 (DB0NA)
set CAT=FA433600000;OS00;CT00;MD02;PC010;
echo Sende Befehl "%CAT%" an %COMPORT%
echo| set /p="%CAT%"> %COMPORT%
"C:\Program Files\SDR-Radio.com (V3)\SDR Console.exe"
